# Generated by Django 5.0.14 on 2026-08-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Software Engineering', 'Software Engineering'), ('Data & AI', 'Data & AI'), ('Cloud & DevOps', 'Cloud & DevOps'), ('Cybersecurity', 'Cybersecurity')], default='Software Engineering', max_length=50)),
                ('icon', models.CharField(default='bi-laptop', help_text='Bootstrap icon class', max_length=50)),
                ('average_salary', models.CharField(default='$95,000 - $155,000', max_length=50)),
                ('market_demand', models.CharField(default='Very High', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Languages', 'Languages'), ('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Databases', 'Databases'), ('DevOps', 'DevOps & Cloud'), ('Data & AI', 'Data & AI'), ('Security', 'Security'), ('Tools', 'Tools & Version Control'), ('Fundamentals', 'Computer Science Fundamentals')], default='Backend', max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('importance', models.CharField(choices=[('HIGH', 'High Priority / Core'), ('MEDIUM', 'Medium Priority / Recommended'), ('LOW', 'Low Priority / Supplementary')], default='HIGH', max_length=20)),
                ('prerequisite_order', models.IntegerField(default=1, help_text='Topological learning order rank')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_skills', to='careers.career')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_careers', to='careers.skill')),
            ],
            options={
                'ordering': ['prerequisite_order', 'id'],
                'unique_together': {('career', 'skill')},
            },
        ),
    ]
