# Generated by Django 5.0.14 on 2026-08-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner (Foundational)'), ('Intermediate', 'Intermediate (Practical Architecture)'), ('Advanced', 'Advanced (Production Scalability)')], default='Intermediate', max_length=20)),
                ('estimated_hours', models.IntegerField(default=12)),
                ('prerequisites', models.TextField(blank=True, help_text='e.g. Basic Java, SQL, REST knowledge')),
                ('starter_guide', models.TextField(blank=True, help_text='Step-by-step implementation milestones')),
                ('github_template_url', models.URLField(blank=True, null=True)),
                ('skills', models.ManyToManyField(related_name='projects', to='careers.skill')),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
    ]
