# Generated by Django 5.0.14 on 2026-08-28 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career_goal', models.CharField(default='Backend Developer', max_length=255)),
                ('experience_level', models.CharField(choices=[('Beginner', 'Beginner (No prior tech experience)'), ('Intermediate', 'Intermediate (Some coding / related degree)'), ('Advanced', 'Advanced (Industry experience / solid foundation)'), ('Professional', 'Professional (Looking to switch or level up)')], default='Intermediate', max_length=30)),
                ('weekly_hours', models.CharField(choices=[('1-5', '1–5 hours (Casual pace)'), ('5-10', '5–10 hours (Standard pace)'), ('10-15', '10–15 hours (Accelerated pace)'), ('15-20', '15–20 hours (Intensive pace)'), ('20+', '20+ hours (Full-time bootcamp pace)')], default='5-10', max_length=20)),
                ('target_timeline', models.CharField(choices=[('1 month', '1 Month (Rapid / Sprint)'), ('3 months', '3 Months (Recommended standard)'), ('6 months', '6 Months (Comprehensive mastery)'), ('1 year', '1 Year (Deep long-term track)')], default='3 months', max_length=20)),
                ('learning_style', models.CharField(choices=[('Videos', 'Video Tutorials & Walkthroughs'), ('Reading', 'Documentation & In-depth Articles'), ('Practice', 'Hands-on Coding Challenges & Katas'), ('Projects', 'Project-based Building'), ('Mixed', 'Balanced Mix of All Methods')], default='Mixed', max_length=20)),
                ('interests', models.TextField(blank=True, help_text='e.g. Distributed Systems, AI Apps, Web Dev')),
                ('learning_history', models.TextField(blank=True, help_text='e.g. Completed Python 101, built portfolio website')),
                ('streak_days', models.IntegerField(default=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner (Familiar with basics)'), ('Intermediate', 'Intermediate (Can build apps/features)'), ('Advanced', 'Advanced (Production mastery)')], default='Intermediate', max_length=20)),
                ('experience_months', models.IntegerField(default=6)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_skills', to='careers.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['skill__name'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
