# Generated by Django 5.0.14 on 2026-08-28 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('resource_type', models.CharField(choices=[('Video', 'Video'), ('Course', 'Course'), ('Documentation', 'Official Documentation'), ('Article', 'Article / Guide'), ('Practice', 'Practice / Exercises'), ('Project', 'Guided Project')], default='Documentation', max_length=30)),
                ('platform', models.CharField(default='Official Docs', help_text='e.g. MDN, freeCodeCamp, Kaggle, LeetCode', max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('estimated_hours', models.FloatField(default=2.0)),
                ('free_or_paid', models.CharField(choices=[('Free', 'Free'), ('Paid', 'Paid')], default='Free', max_length=10)),
                ('rating', models.FloatField(default=4.8)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='careers.skill')),
            ],
            options={
                'ordering': ['skill', 'difficulty', 'title'],
            },
        ),
    ]
